# refs: https://github.com/dalance/procs?tab=readme-ov-file#configuration

[[columns]]
kind = "Pid"
style = "BrightYellow|Yellow"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "User"
style = "BrightGreen|Green"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Separator"
style = "White|BrightBlack"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Tty"
style = "BrightWhite|Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "UsageCpu"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "UsageMem"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "CpuTime"
style = "BrightCyan|Cyan"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "MultiSlot"
style = "ByUnit"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "Separator"
style = "White|BrightBlack"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Command"
style = "BrightWhite|Black"
numeric_search = false
nonnumeric_search = true
align = "Left"

[style]
header = "BrightWhite|Black"
unit = "BrightWhite|Black"
tree = "BrightWhite|Black"

[style.by_percentage]
color_000 = "BrightBlue|Blue"
color_025 = "BrightGreen|Green"
color_050 = "BrightYellow|Yellow"
color_075 = "BrightRed|Red"
color_100 = "BrightRed|Red"

[style.by_state]
color_d = "BrightRed|Red"
color_r = "BrightGreen|Green"
color_s = "BrightBlue|Blue"
color_t = "BrightCyan|Cyan"
color_z = "BrightMagenta|Magenta"
color_x = "BrightMagenta|Magenta"
color_k = "BrightYellow|Yellow"
color_w = "BrightYellow|Yellow"
color_p = "BrightYellow|Yellow"

[style.by_unit]
color_k = "BrightBlue|Blue"
color_m = "BrightGreen|Green"
color_g = "BrightYellow|Yellow"
color_t = "BrightRed|Red"
color_p = "BrightRed|Red"
color_x = "BrightBlue|Blue"

[search]
numeric_search = "Exact"
nonnumeric_search = "Partial"
logic = "And"
case = "Smart"

[display]
show_self = false                        # whether the self process ( procs ) is shown
show_self_parents = false                # whether the parents which have self as the only child process are shown
show_thread = false                      # whether the thread information is shown ( Linux only )
show_thread_in_tree = true               # whether the thread information is shown in tree mode
show_parent_in_tree = true               # whether the parent process is shown in tree mode
show_children_in_tree = true             # whether the children processes are shown in tree mode
show_header = true                       # whether header row is shown
show_footer = false                      # whether footer row is shown
show_kthreads = true                     # whether to show kernel threads
cut_to_terminal = true                   # whether output lines are truncated for output into terminal
cut_to_pager = false                     # whether output lines are truncated for output into pager
cut_to_pipe = false                      # whether output lines are truncated for output into pipe
color_mode = "Auto"
separator = "│"
ascending = "▲"
descending = "▼"
tree_symbols = ["│", "─", "┬", "├", "└"]
abbr_sid = true
theme = "Auto"

[sort]
column = 0
order = "Ascending" # or "Descending"

[docker]
path = "unix://$XDG_RUNTIME_DIR/docker.sock" # local
# path = "unix:///var/run/docker.sock" # global

[pager]
command = 'less -SR' # pager command
mode = "Auto"        # the default behavior of pager usage without --pager commandline option
detect_width = false # whether auto mode detects terminal width overflow
use_builtin = false  # whether built-in pager is used
